#!/bin/bash

# check if script was run as root. exit if false
if [ $UID -ne 0 ]
then
  echo "Please run this script as root."
  exit
fi

#Define Variables
output=$HOME/research/sys_info.txt
ip=$(ip addr |grep inet | tail -2 |head 1)
execs=$(sudo find / -type f -perm 777 2> /dev/null)
cpu=$(lscpu | grep CPU)
disk=$(df -H | head -2)
# define lists to use later
commands=(
  'date'
  'uname -a'
  'hostname -s'
)

files=(
  '/etc/passwd'
  '/etc/shadow'
  '/etc/hosts'

#check for research directory. create if needed
if [ ! -d $HOME/research ]
then
  mkdir $HOME/research
fi

# check for output file. clear it if needed.
if [ -f $output ]
then
 rm $output
fi

#########################################
#start script

echo "A Quick System Audit Script" >> $output
echo "" >> $output

for x in {0..2};
do
   results=$(${commands[$x]})
   echo "Results of "${commands[$x]}" command:" >> $output
   echo $results >> $output
   echo "" >> $output
done

# Distplay Machine type
echo "Machine type info" >> $output
echo -e "$MACHTYPE \n" >> $output

echo -e "Uname info: $(uname -a) \n" >> $output

# Display IP Address info
echo -e "IP info:" >> $output
echo -e "$ip \n" >> $output


echo -e "Hostname: $(hostname -s) \n" >> $output
echo "DNS Servers: " >> $output
cat /etc/resolv.conf >> $output

# Display momory usage
echo "\nMemory Info:" >> $output
free >> $output

#Display cpu usage
echo -e "\nCPU Info:" >> $output
lscpu | grep CPU >> $output

# Display Disk usage
echo -e "\nDisk Usage:" >> $output
df -H | head -2 >> $output

#Display who is logged in
echo -e "\nWho is logged in: \n $(who -a) \n" >> $output
echo -e "\nSUID Files:"

# List exec files
echo -e "\nexec Files:" >> $output
for exec in $execs;
do
  echo $exec
done

# List to 10 processes
echo -e "\nTop 10 Processes" >> $output
ps aux --sort -%mem | awk {'print $1, $2, $3, $4, $11'} | head >> $output

# check the permissions on files
echo -e "\nThe permissions for sensitive /etc files; \n" >> $output
for file in ${files[@]};
do
    ls -l $files >> $output
done

